image: node:latest

stages:
  - installment
  - validation
  #- build
  #- deployment


install:
  stage: installment
  artifacts:
    paths:
      - node_modules/
  script:
    - npm install

test:
  stage: validation
  image: node:latest
  artifacts:
    paths:
      - node_modules/
  script:
    -npm run test



