image: node:latest

stages:
  - install
  - validation
  - build
  - deploy

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/


installment:
  stage: install
  cache:
   <<: *global_cache
   policy: pull
  script:
    - npm install

lint:
  stage: validation
  cache:
   <<: *global_cache
   policy: pull
  script:
    -npm run lint

prettier:
  stage: validation
  cache:
   <<: *global_cache
   policy: pull
  script: 
    -npm run prettier

test:
  stage: validation
  cache:
   <<: *global_cache 
  script:
    -npm run test

build:
  stage: build
  cache:
   <<: *global_cache 
  script:
    -npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: false
  artifacts:
    expire_in: 1 week
    paths:
      - out/


deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod 


