image: node:latest

stages:
  - install
  - validation
  - build
  - deploy

installment:
  stage: install
  script:
    - npm install

lint:
  stage: validation
  script:
    -npm run lint

prettier:
  stage: validation
  script: 
    -npm run prettier

test:
  stage: validation
  script:
    -npm run test

build:
  stage: build
  script:
    -npm run build
