image: node:latest

stages:
  - installment
  - validation
  #- build
  #- deployment

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/

installment:
  stage: installment
  cache:
   <<: *global_cache
  script:
    - npm install

lint:
  stage: validation
  cache:
   <<: *global_cache
   policy: pull
  script:
    -npm run lint



