# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - run: |
           npm install
           npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - run: |
            npm install
            npm run test
  prettier:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - run: |
            npm install
            npm run prettier
  build:
    runs-on: ubuntu-latest
    needs: [lint,test,prettier]
    steps: 
      - uses: actions/checkout@v3
      - run: echo "building"
      
  deploy:   
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v3
      - run: echo "deploy"
    
